# Generated by Django 4.2.7 on 2023-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_shoes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
